import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/Navbar";
import Container from "./Components/Container";
import Footer from "./Components/Footer";
import SessionWrapper from "./Components/SessionWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
        
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SessionWrapper>
          <Container>
            <NavBar />
          </Container>

          <div className="bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900">
            <Container> {children} </Container>{" "}
          </div>
          <Footer></Footer>
          </SessionWrapper>
        </body>
       
    
    </html>
  );
}
